[project]
name = "learn-langgraph"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.24.0",
    "langchain-google-genai>=4.4.0",
    "python-dotenv>=1.2.3",
    "langchain",
    "langchain-core",
    "langchain-community",
    "langchain-groq",
    "pypdf",
    "pydantic",
    "beautifulsoup4",
    "langchain_huggingface",
    "sentence_transformers",
    "langchain_chroma",
]
